import assert from 'node:assert/strict';
import { mkdtemp, cp, symlink, writeFile, readFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { spawn, execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { createServer } from 'node:net';
import { chromium } from 'playwright';
const exec=promisify(execFile), dir=await mkdtemp(join(tmpdir(),'publisher-browser-')), root=join(dir,'site'),remote=join(dir,'remote.git');
let server,browser,page,logs='';const errors=[];
const git=async(...args)=>(await exec('git',args,{cwd:root})).stdout.trim();
try {
 await cp('src',join(root,'src'),{recursive:true});await cp('package.json',join(root,'package.json'));
 await symlink(join(process.cwd(),'node_modules'),join(root,'node_modules'),'dir');await symlink(join(process.cwd(),'public'),join(root,'public'),'dir');
 await writeFile(join(root,'astro.config.mjs'), `import {defineConfig} from 'astro/config'; import writer from './src/editor/integration.mjs'; export default defineConfig({output:'static', vite:{cacheDir:'.vite-publish-test'}, integrations:[writer({publishOptions:{deploy:async({phase})=>{await new Promise(r=>setTimeout(r,1800));phase('verifying','Checking the live website…');await new Promise(r=>setTimeout(r,1800));}}})]});`);
 await exec('git',['init','--bare',remote]);await git('init','-b','main');await git('config','user.name','Browser test');await git('config','user.email','test@example.com');
 await git('add','src','package.json','astro.config.mjs');await git('commit','-m','initial');await git('remote','add','origin',remote);await git('push','-u','origin','main');
 const original=await git('rev-parse','HEAD');
 const probe=createServer();await new Promise(r=>probe.listen(0,'127.0.0.1',r));const port=probe.address().port;await new Promise(r=>probe.close(r));const base=`http://127.0.0.1:${port}`;
 server=spawn(process.execPath,[join(process.cwd(),'node_modules/astro/bin/astro.mjs'),'dev','--ignore-lock','--host','127.0.0.1','--port',String(port)],{cwd:root,stdio:['ignore','pipe','pipe']});
 server.stdout.on('data',x=>logs+=x);server.stderr.on('data',x=>logs+=x);
 let ready=false;for(let i=0;i<100;i++){try{if((await fetch(base,{signal:AbortSignal.timeout(1000)})).ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,100));}assert.ok(ready,logs);
 browser=await chromium.launch();page=await browser.newPage();page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/write');await page.locator('#status').filter({hasText:'Saved locally'}).waitFor();await page.waitForTimeout(500);
 assert.equal(await page.getByRole('button',{name:'Publish',exact:true}).isEnabled(),true,'Publish must become available after sources are loaded');
 await page.getByRole('button',{name:'Markdown view',exact:true}).click();await page.locator('#markdown').fill('- locally saved dummy');
 await page.locator('#status').filter({hasText:'Saved locally'}).waitFor();assert.equal(await git('rev-parse','origin/main'),original,'Autosave never pushes');
 await page.locator('#markdown').fill('- latest dummy');await page.locator('#section').selectOption('contact');await page.locator('#markdown').fill('- contact dummy');
 await page.getByRole('button',{name:'Publish',exact:true}).click();
 await page.locator('#publish-status').filter({hasText:'Deploying'}).waitFor();
 assert.equal(await page.locator('#markdown').isDisabled(),true,'Publishing locks further edits until the snapshot is sent');
 assert.equal(await git('show','HEAD:src/content/home.md'),'- latest dummy');assert.equal(await git('show','HEAD:src/content/contact.md'),'- contact dummy');
 await page.reload();await page.locator('#publish-status').filter({hasText:'Live on aayush.world'}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Publish',exact:true}).isEnabled(),true);
 await page.getByRole('button',{name:'Markdown view',exact:true}).click();await page.locator('#markdown').fill('- retry dummy');
 await git('remote','set-url','origin',join(dir,'missing.git'));
 await page.getByRole('button',{name:'Publish',exact:true}).click();await page.locator('#publish-status').filter({hasText:'Could not send'}).waitFor();
 assert.equal(await page.locator('#markdown').inputValue(),'- retry dummy');const retryCommit=await git('rev-parse','HEAD');
 await git('remote','set-url','origin',remote);await page.getByRole('button',{name:'Try publishing again',exact:true}).click();await page.locator('#publish-status').filter({hasText:'Live on aayush.world'}).waitFor();assert.equal(await git('rev-parse','HEAD'),retryCommit);
 const beforeFailedSave=await git('rev-parse','origin/main');let publishPosts=0;
 page.on('request',request=>{if(request.url().endsWith('/__writer/publish')&&request.method()==='POST')publishPosts++;});
 await page.route('**/__writer/content',route=>route.request().method()==='POST'?route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Test save failed'})}):route.continue());
 await page.locator('#markdown').fill('- unsaved recovery dummy');await page.getByRole('button',{name:'Publish',exact:true}).click();
 await page.locator('#publish-status').filter({hasText:/Could not save|Resolve the unsaved/}).waitFor();
 assert.equal(publishPosts,0,'A failed local save must stop before the publish request');assert.equal(await git('rev-parse','origin/main'),beforeFailedSave);
 await page.unroute('**/__writer/content');await page.getByRole('button',{name:'Retry save',exact:true}).click();await page.locator('#status').filter({hasText:'Saved locally'}).waitFor();
 const denied=await fetch(base+'/__writer/publish',{method:'POST',headers:{Origin:'https://example.com','Content-Type':'application/json'},body:'{}'});assert.equal(denied.status,403);
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.screenshot({path:'/tmp/publish-writing-room-mobile.png',fullPage:true});assert.deepEqual(errors,[]);
 assert.equal(await readFile(join(root,'src/content/home.md'),'utf8'),'- unsaved recovery dummy');
 console.log('Publish browser: autosave stays local, all-region flush, real Git push, progress, reload, failure/retry, origin checks, mobile passed (deployment boundary simulated).');
} catch(error) { console.error(JSON.stringify({status:await page?.locator('#status').textContent().catch(()=>null),errors,serverLog:logs.slice(-2000)})); throw error; } finally {await browser?.close();server?.kill();await new Promise(r=>setTimeout(r,300));await rm(dir,{recursive:true,force:true});}
